#Heart Disease Prediction


In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [3]:
path=r"Merged.csv"
mergeddata = pd.read_csv(path)

In [ ]:
mergeddata.head()

age  sex  chest  ...  number_of_major_vessels  thal  target
0   70    1      4  ...                        3     3       1
1   67    0      3  ...                        0     7       0
2   57    1      2  ...                        0     7       1
3   64    1      4  ...                        1     7       0
4   74    0      2  ...                        1     3       0

[5 rows x 14 columns]

In [4]:
train , test = train_test_split(mergeddata,test_size = .3,random_state = 123)
X_train = train[[x for x in train.columns if x not in ["target"]]]
y_train = train[["target"]]
X_test  = test[[x for x in test.columns if x not in ["target"]]]
y_test  = test[["target"]]

In [5]:
from sklearn.ensemble import RandomForestClassifier 
RF = RandomForestClassifier(n_estimators=5)
RF.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=5,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [6]:
y_pred= RF.predict(X_test)
accuracy_M_RF = accuracy_score(y_test, y_pred)
print("Accuracy", accuracy_M_RF*100)
print("Confusion Matrix")
print(confusion_matrix(y_test,y_pred)) 
print("Classification Report") 
print(classification_report (y_test, y_pred)) 

Accuracy 91.22807017543859
Confusion Matrix
[[76  9]
 [ 6 80]]
Classification Report
              precision    recall  f1-score   support

           0       0.93      0.89      0.91        85
           1       0.90      0.93      0.91        86

    accuracy                           0.91       171
   macro avg       0.91      0.91      0.91       171
weighted avg       0.91      0.91      0.91       171



In [ ]:
X_test

age  sex  chest  ...  slope  number_of_major_vessels  thal
427   60    1      4  ...      2                        2     7
436   35    1      4  ...      1                        0     7
248   60    1      3  ...      2                        0     3
236   53    0      4  ...      1                        0     3
295   50    0      3  ...      2                        0     3
..   ...  ...    ...  ...    ...                      ...   ...
42    44    1      3  ...      1                        0     3
410   59    1      1  ...      2                        0     7
41    62    0      4  ...      1                        0     3
557   44    1      4  ...      3                        0     6
348   48    1      2  ...      2                        0     3

[171 rows x 13 columns]

In [7]:
RF.predict([[60,1,4,140,293,0,2,170,0,1.2,2,2,7]])

array([1])

In [ ]:
RF.predict([[48,1,2,130,245,0,2,180,0,0.2,2,0,3]])

array([0])

In [ ]:
y_pred=RF.predict(X_test)
y_pred

array([1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0])

In [ ]:
pd.DataFrame(np.c_[X_test, y_test, y_pred])

0    1    2      3      4    5    6   ...   8    9    10   11   12   13   14
0    60.0  1.0  4.0  140.0  293.0  0.0  2.0  ...  0.0  1.2  2.0  2.0  7.0  1.0  1.0
1    35.0  1.0  4.0  126.0  282.0  0.0  2.0  ...  1.0  0.0  1.0  0.0  7.0  1.0  1.0
2    60.0  1.0  3.0  140.0  185.0  0.0  2.0  ...  0.0  3.0  2.0  0.0  3.0  1.0  0.0
3    53.0  0.0  4.0  138.0  234.0  0.0  2.0  ...  0.0  0.0  1.0  0.0  3.0  0.0  0.0
4    50.0  0.0  3.0  120.0  219.0  0.0  0.0  ...  0.0  1.6  2.0  0.0  3.0  0.0  0.0
..    ...  ...  ...    ...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
166  44.0  1.0  3.0  130.0  233.0  0.0  0.0  ...  1.0  0.4  1.0  0.0  3.0  0.0  0.0
167  59.0  1.0  1.0  170.0  288.0  0.0  2.0  ...  0.0  0.2  2.0  0.0  7.0  1.0  0.0
168  62.0  0.0  4.0  124.0  209.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  3.0  0.0  0.0
169  44.0  1.0  4.0  120.0  169.0  0.0  0.0  ...  1.0  2.8  3.0  0.0  6.0  1.0  1.0
170  48.0  1.0  2.0  130.0  245.0  0.0  2.0  ...  0.0  0.2  2.0  0.0  3.0  0.0  0.0

[171 rows x 15 columns]

In [8]:
import joblib
joblib.dump(RF, "heart_disease_model.pkl")

['heart_disease_model.pkl']